import {StyleSheet} from 'react-native';
import {colors, radii, space} from '@/ui/theme';

export const adminStyles = StyleSheet.create({
  root: {flex: 1, backgroundColor: colors.bg},
  back: {padding: 8},
  tabs: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: space.md,
    paddingBottom: space.sm,
  },
  tab: {
    flex: 1,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
  },
  tabOn: {backgroundColor: colors.navy, borderColor: colors.navy},
  tabText: {fontWeight: '800', color: colors.navy, fontSize: 12},
  tabTextOn: {color: '#fff'},
  body: {padding: space.md, paddingBottom: 48, gap: 8},
  card: {
    backgroundColor: colors.white,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: space.sm,
    gap: 6,
  },
  rowName: {fontWeight: '800', color: colors.navy, fontSize: 15},
  rowMeta: {color: colors.muted, fontWeight: '600', fontSize: 12},
  actions: {flexDirection: 'row', gap: 8, marginTop: 4},
  action: {flex: 1},
  empty: {color: colors.muted, fontWeight: '600'},
  coordRow: {flexDirection: 'row', gap: 8},
  clearForm: {
    textAlign: 'center',
    color: colors.muted,
    fontWeight: '700',
    paddingVertical: 8,
  },
  chips: {flexDirection: 'row', gap: 8, paddingVertical: 4},
  chip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chipOn: {backgroundColor: colors.navy, borderColor: colors.navy},
  chipText: {fontWeight: '700', color: colors.navy, fontSize: 12},
  chipTextOn: {color: '#fff'},
});
